/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MiningRouteImport } from './routes/mining'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiTradingRouteImport } from './routes/ai-trading'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSmsTestRouteImport } from './routes/admin.sms-test'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as ApiPublicHooksVerifyDepositsRouteImport } from './routes/api/public/hooks/verify-deposits'
import { Route as ApiPublicHooksMatureInvestmentsRouteImport } from './routes/api/public/hooks/mature-investments'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoute = MiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTradingRoute = AiTradingRouteImport.update({
  id: '/ai-trading',
  path: '/ai-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSmsTestRoute = AdminSmsTestRouteImport.update({
  id: '/sms-test',
  path: '/sms-test',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksVerifyDepositsRoute =
  ApiPublicHooksVerifyDepositsRouteImport.update({
    id: '/api/public/hooks/verify-deposits',
    path: '/api/public/hooks/verify-deposits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMatureInvestmentsRoute =
  ApiPublicHooksMatureInvestmentsRouteImport.update({
    id: '/api/public/hooks/mature-investments',
    path: '/api/public/hooks/mature-investments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/ai-trading': typeof AiTradingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mining': typeof MiningRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/sms-test': typeof AdminSmsTestRoute
  '/api/public/hooks/mature-investments': typeof ApiPublicHooksMatureInvestmentsRoute
  '/api/public/hooks/verify-deposits': typeof ApiPublicHooksVerifyDepositsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/ai-trading': typeof AiTradingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mining': typeof MiningRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/sms-test': typeof AdminSmsTestRoute
  '/api/public/hooks/mature-investments': typeof ApiPublicHooksMatureInvestmentsRoute
  '/api/public/hooks/verify-deposits': typeof ApiPublicHooksVerifyDepositsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/ai-trading': typeof AiTradingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mining': typeof MiningRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/sms-test': typeof AdminSmsTestRoute
  '/api/public/hooks/mature-investments': typeof ApiPublicHooksMatureInvestmentsRoute
  '/api/public/hooks/verify-deposits': typeof ApiPublicHooksVerifyDepositsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate'
    | '/ai-trading'
    | '/contact'
    | '/dashboard'
    | '/deposit'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/mining'
    | '/privacy'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/staking'
    | '/support'
    | '/terms'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/admin/operations'
    | '/admin/reset-password'
    | '/admin/sms-test'
    | '/api/public/hooks/mature-investments'
    | '/api/public/hooks/verify-deposits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate'
    | '/ai-trading'
    | '/contact'
    | '/dashboard'
    | '/deposit'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/mining'
    | '/privacy'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/staking'
    | '/support'
    | '/terms'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/admin/operations'
    | '/admin/reset-password'
    | '/admin/sms-test'
    | '/api/public/hooks/mature-investments'
    | '/api/public/hooks/verify-deposits'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate'
    | '/ai-trading'
    | '/contact'
    | '/dashboard'
    | '/deposit'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/mining'
    | '/privacy'
    | '/referrals'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/staking'
    | '/support'
    | '/terms'
    | '/transactions'
    | '/wallet'
    | '/withdraw'
    | '/admin/operations'
    | '/admin/reset-password'
    | '/admin/sms-test'
    | '/api/public/hooks/mature-investments'
    | '/api/public/hooks/verify-deposits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  AiTradingRoute: typeof AiTradingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MiningRoute: typeof MiningRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferralsRoute: typeof ReferralsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StakingRoute: typeof StakingRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRoute
  ApiPublicHooksMatureInvestmentsRoute: typeof ApiPublicHooksMatureInvestmentsRoute
  ApiPublicHooksVerifyDepositsRoute: typeof ApiPublicHooksVerifyDepositsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining': {
      id: '/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof MiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-trading': {
      id: '/ai-trading'
      path: '/ai-trading'
      fullPath: '/ai-trading'
      preLoaderRoute: typeof AiTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sms-test': {
      id: '/admin/sms-test'
      path: '/sms-test'
      fullPath: '/admin/sms-test'
      preLoaderRoute: typeof AdminSmsTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/verify-deposits': {
      id: '/api/public/hooks/verify-deposits'
      path: '/api/public/hooks/verify-deposits'
      fullPath: '/api/public/hooks/verify-deposits'
      preLoaderRoute: typeof ApiPublicHooksVerifyDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mature-investments': {
      id: '/api/public/hooks/mature-investments'
      path: '/api/public/hooks/mature-investments'
      fullPath: '/api/public/hooks/mature-investments'
      preLoaderRoute: typeof ApiPublicHooksMatureInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSmsTestRoute: typeof AdminSmsTestRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOperationsRoute: AdminOperationsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSmsTestRoute: AdminSmsTestRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  AiTradingRoute: AiTradingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MiningRoute: MiningRoute,
  PrivacyRoute: PrivacyRoute,
  ReferralsRoute: ReferralsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StakingRoute: StakingRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRoute,
  ApiPublicHooksMatureInvestmentsRoute: ApiPublicHooksMatureInvestmentsRoute,
  ApiPublicHooksVerifyDepositsRoute: ApiPublicHooksVerifyDepositsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
